# Site settings
title: Stephen Wai
email: stevewai@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://stephenwai.com" # the base hostname & protocol for your site
twitter_username: swaiing
github_username:  swaiing
linkedin_url:  stephenwai
google_analytics_id:  UA-22934935-2

# Build settings
markdown: kramdown
